config/routes.rb
Rails.application.routes.draw do
  resources :usuarios
  resources :licitacions
  resources :users
  resources :posts
  # get 'pages/home'
  get 'pages/about', to: 'pages#about'
  get 'pages/dashboard', to: 'pages#dashboard'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  get 'usuarios/index', to: 'usuarios#index'
  get 'licitacions/index', to: 'licitacions#index'
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/licitacion.rb
class Licitacion < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
end

app/controllers/licitacions_controller.rb
class LicitacionsController < ApplicationController
  before_action :set_licitacion, only: %i[ show edit update destroy ]

  # GET /licitacions or /licitacions.json
  def index
    @licitacions = Licitacion.all
  end

  # GET /licitacions/1 or /licitacions/1.json
  def show
  end

  # GET /licitacions/new
  def new
    @licitacion = Licitacion.new
  end

  # GET /licitacions/1/edit
  def edit
  end

  # POST /licitacions or /licitacions.json
  def create
    @licitacion = Licitacion.new(licitacion_params)

    respond_to do |format|
      if @licitacion.save
        format.html { redirect_to licitacion_url(@licitacion), notice: "Licitacion was successfully created." }
        format.json { render :show, status: :created, location: @licitacion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @licitacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /licitacions/1 or /licitacions/1.json
  def update
    respond_to do |format|
      if @licitacion.update(licitacion_params)
        format.html { redirect_to licitacion_url(@licitacion), notice: "Licitacion was successfully updated." }
        format.json { render :show, status: :ok, location: @licitacion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @licitacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /licitacions/1 or /licitacions/1.json
  def destroy
    @licitacion.destroy

    respond_to do |format|
      format.html { redirect_to licitacions_url, notice: "Licitacion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_licitacion
      @licitacion = Licitacion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def licitacion_params
      params.require(:licitacion).permit(:title, :descripcion, :fecha)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: %i[ show edit update destroy ]

  # GET /usuarios or /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1 or /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios or /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario was successfully created." }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1 or /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario was successfully updated." }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1 or /usuarios/1.json
  def destroy
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :apellido, :mail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/licitacions_helper.rb
module LicitacionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="py-5">
    <div class="row">
      <div class="col-6 col-md-2 mb-3">
        <h5>Section</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
        </ul>
      </div>

      <div class="col-6 col-md-2 mb-3">
        <h5>Section</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
        </ul>
      </div>

      <div class="col-6 col-md-2 mb-3">
        <h5>Section</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
        </ul>
      </div>

      <div class="col-md-5 offset-md-1 mb-3">
        <form>
          <h5>Subscribe to our newsletter</h5>
          <p>Monthly digest of what's new and exciting from us.</p>
          <div class="d-flex flex-column flex-sm-row w-100 gap-2">
            <label for="newsletter1" class="visually-hidden">Email address</label>
            <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
            <button class="btn btn-primary" type="button">Subscribe</button>
          </div>
        </form>
      </div>
    </div>

    <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
      <p>&copy; 2022 Company, Inc. All rights reserved.</p>
      <ul class="list-unstyled d-flex">
        <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
        <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
        <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
      </ul>
    </div>
  </footer>
</div>


    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "WebApp", root_path, class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
           <%= link_to "Home", root_path, class:'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to "About", pages_about_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Licitaciones", licitacions_path, class:'nav-link' %>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Profile
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Edit profile</a></li>
            <li><a class="dropdown-item" href="#">configuration</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Licitar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <%= render 'layouts/navbar'%>
      <%= yield %>
      <%= render 'layouts/footer'%>
    </main>
  </body>
</html>

app/views/licitacions/_form.html.erb
<%= form_with(model: licitacion) do |form| %>
  <% if licitacion.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(licitacion.errors.count, "error") %> prohibited this licitacion from being saved:</h2>

      <ul>
        <% licitacion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_area :descripcion %>
  </div>

  <div>
    <%= form.label :fecha, style: "display: block" %>
    <%= form.date_field :fecha %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/licitacions/_licitacion.html.erb
<div id="<%= dom_id licitacion %>">
  <p>
    <strong>Title:</strong>
    <%= licitacion.title %>
  </p>

  <p>
    <strong>Descripcion:</strong>
    <%= licitacion.descripcion %>
  </p>

  <p>
    <strong>Fecha:</strong>
    <%= licitacion.fecha %>
  </p>

</div>

app/views/licitacions/edit.html.erb
<h1>Editing licitacion</h1>

<%= render "form", licitacion: @licitacion %>

<br>

<div>
  <%= link_to "Show this licitacion", @licitacion %> |
  <%= link_to "Back to licitacions", licitacions_path %>
</div>

app/views/licitacions/index.html.erb
<p style="color: green"><%= notice %></p>
<div class=container>
<h1>Licitacions</h1>

<div id="licitacions">
  <% @licitacions.each do |licitacion| %>
    <%= render licitacion %>
    <p>
      <%= link_to "Show this licitacion", licitacion %>
    </p>
  <% end %>
</div>

<%= link_to "New licitacion", new_licitacion_path %>
</div>

app/views/licitacions/new.html.erb
<h1>New licitacion</h1>

<%= render "form", licitacion: @licitacion %>

<br>

<div>
  <%= link_to "Back to licitacions", licitacions_path %>
</div>

app/views/licitacions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @licitacion %>

<div>
  <%= link_to "Edit this licitacion", edit_licitacion_path(@licitacion) %> |
  <%= link_to "Back to licitacions", licitacions_path %>

  <%= button_to "Destroy this licitacion", @licitacion, method: :delete %>
</div>

app/views/pages/about.html.erb
<div class="container">
<h1>Describe Myselft</h1>
<p>Sobre mi y otras cosas</p>
<%= link_to "Home", root_path %>
</div>

app/views/pages/dashboard.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.98.0">
    <title>Dashboard Template · Bootstrap v5.2</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/dashboard/">

<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="dashboard.css" rel="stylesheet">
  </head>
  <body>

<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="#">Company name</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100 rounded-0 border-0" type="text" placeholder="Search" aria-label="Search">
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <a class="nav-link px-3" href="#">Sign out</a>
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">
              <span data-feather="home" class="align-text-bottom"></span>
              Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file" class="align-text-bottom"></span>
              Orders
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="shopping-cart" class="align-text-bottom"></span>
              Products
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users" class="align-text-bottom"></span>
              Customers
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2" class="align-text-bottom"></span>
              Reports
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers" class="align-text-bottom"></span>
              Integrations
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted text-uppercase">
          <span>Saved reports</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle" class="align-text-bottom"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text" class="align-text-bottom"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text" class="align-text-bottom"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text" class="align-text-bottom"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text" class="align-text-bottom"></span>
              Year-end sale
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
          </div>
          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar" class="align-text-bottom"></span>
            This week
          </button>
        </div>
      </div>

      <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

      <h2>Section title</h2>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Header</th>
              <th scope="col">Header</th>
              <th scope="col">Header</th>
              <th scope="col">Header</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1,001</td>
              <td>random</td>
              <td>data</td>
              <td>placeholder</td>
              <td>text</td>
            </tr>
            <tr>
              <td>1,002</td>
              <td>placeholder</td>
              <td>irrelevant</td>
              <td>visual</td>
              <td>layout</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>data</td>
              <td>rich</td>
              <td>dashboard</td>
              <td>tabular</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>information</td>
              <td>placeholder</td>
              <td>illustrative</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,004</td>
              <td>text</td>
              <td>random</td>
              <td>layout</td>
              <td>dashboard</td>
            </tr>
            <tr>
              <td>1,005</td>
              <td>dashboard</td>
              <td>irrelevant</td>
              <td>text</td>
              <td>placeholder</td>
            </tr>
            <tr>
              <td>1,006</td>
              <td>dashboard</td>
              <td>illustrative</td>
              <td>rich</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,007</td>
              <td>placeholder</td>
              <td>tabular</td>
              <td>information</td>
              <td>irrelevant</td>
            </tr>
            <tr>
              <td>1,008</td>
              <td>random</td>
              <td>data</td>
              <td>placeholder</td>
              <td>text</td>
            </tr>
            <tr>
              <td>1,009</td>
              <td>placeholder</td>
              <td>irrelevant</td>
              <td>visual</td>
              <td>layout</td>
            </tr>
            <tr>
              <td>1,010</td>
              <td>data</td>
              <td>rich</td>
              <td>dashboard</td>
              <td>tabular</td>
            </tr>
            <tr>
              <td>1,011</td>
              <td>information</td>
              <td>placeholder</td>
              <td>illustrative</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,012</td>
              <td>text</td>
              <td>placeholder</td>
              <td>layout</td>
              <td>dashboard</td>
            </tr>
            <tr>
              <td>1,013</td>
              <td>dashboard</td>
              <td>irrelevant</td>
              <td>text</td>
              <td>visual</td>
            </tr>
            <tr>
              <td>1,014</td>
              <td>dashboard</td>
              <td>illustrative</td>
              <td>rich</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,015</td>
              <td>random</td>
              <td>tabular</td>
              <td>information</td>
              <td>text</td>
            </tr>
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>


    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

      <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="dashboard.js"></script>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
<h1>Mis Licitaciones</h1>
<p>You can read more about me, or checkout my blog</p>
<!-- <a href="pages/about">About me</a> -->
<div class="container">
<div class="card">
  <div class="card-header">
    Featured
  </div>
  <div class="card-body">
    <h5 class="card-title">Sistema de gestión de Licitaciones</h5>
    <p class="card-text">El Sistema de Gestión de Licitaciones es una solución tecnológica que permite a las empresas realizar un adecuado seguimiento y control de las Licitaciones públicas Nacionales e Internacionales en las cuales participan.</p>

<%= link_to "Gestionar", pages_dashboard_path, class:"btn btn-primary" %>
  </div>
</div>
</div>
<%= link_to "About Me.", pages_about_path %>
<%= link_to "Dashabord", pages_dashboard_path %>
</div>

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario) do |form| %>
  <% if usuario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% usuario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :apellido, style: "display: block" %>
    <%= form.text_field :apellido %>
  </div>

  <div>
    <%= form.label :mail, style: "display: block" %>
    <%= form.text_field :mail %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/usuarios/_usuario.html.erb
<div id="<%= dom_id usuario %>">
  <p>
    <strong>Nombre:</strong>
    <%= usuario.nombre %>
  </p>

  <p>
    <strong>Apellido:</strong>
    <%= usuario.apellido %>
  </p>

  <p>
    <strong>Mail:</strong>
    <%= usuario.mail %>
  </p>

</div>

app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Show this usuario", @usuario %> |
  <%= link_to "Back to usuarios", usuarios_path %>
</div>

app/views/usuarios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Lista de usuarios registrados</h1>

<div id="usuarios">
  <% @usuarios.each do |usuario| %>
    <%= render usuario %>
    <p>
      <%= link_to "Show this usuario", usuario %>
    </p>
  <% end %>
</div>

<%= link_to "New usuario", new_usuario_path %>
<%= link_to "Home", root_path %>
<%= link_to "Usuarios", usuarios_path %>

app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Back to usuarios", usuarios_path %>
</div>

app/views/usuarios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @usuario %>

<div>
  <%= link_to "Edit this usuario", edit_usuario_path(@usuario) %> |
  <%= link_to "Back to usuarios", usuarios_path %>

  <%= button_to "Destroy this usuario", @usuario, method: :delete %>
</div>